### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Starbors** [theADAMJR/1PG#4]
failed to start application on chillers.glitch.me

  This is most likely because your project has a code error.
  Check your project logs, fix the error and try again.  
and here is the log good sir
`/app/handlers/events/message-event.js:10
    if (!msg?.guild) return;
             ^
SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
at Object.<anonymous> (/app/handlers/event-handler.js:10:17)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
at Object.<anonymous> (/app/bot.js:16:1)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
/app/handlers/events/message-event.js:10
    if (!msg?.guild) return;
             ^
SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
at Object.<anonymous> (/app/handlers/event-handler.js:10:17)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
at Object.<anonymous> (/app/bot.js:16:1)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
/app/handlers/events/message-event.js:10
    if (!msg?.guild) return;
             ^
SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
at Object.<anonymous> (/app/handlers/event-handler.js:10:17)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
at Object.<anonymous> (/app/bot.js:16:1)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)`

**Comment by Starbors** [comment]
https://chillers.glitch.me/ is the website >:D

**Comment by theADAMJR** [comment]
The project requires Node v14 as it uses optional chaining. https://glitch.com/edit/#!/1pg-demo?path=README.md%3A1%3A0

or you could replace `msg?.guild` with `msg && msg.guild`

**Comment by Starbors** [comment]
Ok so            l remixed your project and then lm gonna test it ty!

**Comment by Starbors** [comment]
and wait Should l change   "dashboard": {
      "url": "http://localhost:3000"
  },
  "mongoURL": "mongodb://localhost/1PG"
}?

**Comment by theADAMJR** [comment]
It should be changed to your Glitch URL.

**Comment by Starbors** [comment]
Woah so it works! can you just tell me how the set prefix stuff works?https://chiller-bot.glitch.me/ ty!

**Comment by theADAMJR** [comment]
The set prefix command did not work but I did not find the cause of the problem. It can be done via the dashboard though. This project is currently a prototype and should soon be functional (after the course). There will be a 1PG update with more features in the near future.
